name: petfight
description: "PetFight App."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  url_launcher: ^6.3.0
  auto_size_text: ^3.0.0
  provider: ^6.1.2
  http: ^1.2.1
  telegram_web_app: ^0.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/background.png
    - assets/task.png
    - assets/friends.png

  fonts:
    - family: Boxtoon
      fonts:
        - asset: fonts/Boxtoon-Regular.ttf

